name: Deploy book

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'

jobs:
  deploy:
    name: Deploy book on gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install mdBook
        uses: peaceiris/actions-mdbook@v1
      - name: Render book
        run: |
          mdbook build -d gh-pages docs/en
          mkdir gh-pages
          mv docs/en/gh-pages gh-pages/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          emptyCommits: true
          keepFiles: false
        env:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
